# Generated by Django 5.0.14 on 2026-05-12 12:27

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='phone number')),
                ('is_landlord', models.BooleanField(default=False, verbose_name='landlord status')),
                ('is_tenant', models.BooleanField(default=False, verbose_name='tenant status')),
                ('is_vendor', models.BooleanField(default=False, verbose_name='vendor status')),
                ('email_verified', models.BooleanField(default=False, verbose_name='email verified')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='phone verified')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'accounts_user',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', apps.accounts.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LandlordProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=15, verbose_name='phone number')),
                ('id_number', models.CharField(blank=True, max_length=20, verbose_name='ID number')),
                ('kra_pin', models.CharField(blank=True, max_length=15, verbose_name='KRA PIN')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='bank name')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='bank account')),
                ('subscription_tier', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20, verbose_name='subscription tier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'landlord profile',
                'verbose_name_plural': 'landlord profiles',
                'db_table': 'accounts_landlord_profile',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=15, verbose_name='phone number')),
                ('emergency_name', models.CharField(blank=True, max_length=150, verbose_name='emergency contact name')),
                ('emergency_phone', models.CharField(blank=True, max_length=15, verbose_name='emergency contact phone')),
                ('employer_name', models.CharField(blank=True, max_length=150, verbose_name='employer name')),
                ('employer_phone', models.CharField(blank=True, max_length=15, verbose_name='employer phone')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='monthly income')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'tenant profile',
                'verbose_name_plural': 'tenant profiles',
                'db_table': 'accounts_tenant_profile',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
