# Generated by Django 5.0.14 on 2026-05-10 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landlordprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'landlord profile', 'verbose_name_plural': 'landlord profiles'},
        ),
        migrations.AlterModelOptions(
            name='tenantprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'tenant profile', 'verbose_name_plural': 'tenant profiles'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='landlordprofile',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, verbose_name='bank account'),
        ),
        migrations.AlterField(
            model_name='landlordprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='bank name'),
        ),
        migrations.AlterField(
            model_name='landlordprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='landlordprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID number'),
        ),
        migrations.AlterField(
            model_name='landlordprofile',
            name='kra_pin',
            field=models.CharField(blank=True, max_length=15, verbose_name='KRA PIN'),
        ),
        migrations.AlterField(
            model_name='landlordprofile',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='landlordprofile',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20, verbose_name='subscription tier'),
        ),
        migrations.AlterField(
            model_name='landlordprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_profile', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='emergency_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='emergency contact name'),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='emergency contact phone'),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='employer_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='employer name'),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='employer_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='employer phone'),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='monthly income'),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='email verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_landlord',
            field=models.BooleanField(default=False, verbose_name='landlord status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_tenant',
            field=models.BooleanField(default=False, verbose_name='tenant status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_vendor',
            field=models.BooleanField(default=False, verbose_name='vendor status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='phone verified'),
        ),
    ]
