name: zia-property

services:
  db:
    container_name: zia-db
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ziaproperty
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    container_name: zia-redis
    image: redis:7
    ports:
      - "6381:6379"
  web:
    container_name: zia-web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery:
    container_name: zia-worker
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
