# Generated by Django 5.0.14 on 2026-05-14 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('commercial', 'Commercial'), ('mixed', 'Mixed Use')], max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('rules', models.TextField(blank=True, default='')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('photo_gallery', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_listed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(limit_choices_to={'user_type': 'landlord'}, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=50)),
                ('unit_type', models.CharField(choices=[('studio', 'Studio'), ('1_bedroom', '1 Bedroom'), ('2_bedroom', '2 Bedroom'), ('3_bedroom', '3 Bedroom'), ('4_bedroom', '4 Bedroom'), ('shop', 'Shop'), ('office', 'Office'), ('warehouse', 'Warehouse')], max_length=50)),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('square_footage', models.IntegerField(blank=True, null=True)),
                ('floor_number', models.IntegerField(blank=True, null=True)),
                ('is_furnished', models.BooleanField(default=False)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit_terms', models.TextField(blank=True, default='')),
                ('unit_amenities', models.JSONField(blank=True, default=list)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('video_tour', models.URLField(blank=True, default='')),
                ('is_available', models.BooleanField(default=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('listing_title', models.CharField(blank=True, default='', max_length=255)),
                ('listing_description', models.TextField(blank=True, default='')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property')),
            ],
            options={
                'ordering': ['unit_number'],
                'unique_together': {('building', 'unit_number')},
            },
        ),
    ]
