# Generated by Django 5.0.14 on 2026-05-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_cover_photo_property_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['floor_number', 'unit_number']},
        ),
        migrations.RemoveField(
            model_name='unit',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='base_rent',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='floor',
        ),
        migrations.AddField(
            model_name='unit',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='deposit_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='floor_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='is_furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='listing_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='listing_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='photos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='unit',
            name='video_tour',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('studio', 'Studio'), ('1_bedroom', '1 Bedroom'), ('2_bedroom', '2 Bedroom'), ('3_bedroom', '3 Bedroom'), ('4_bedroom', '4 Bedroom'), ('shop', 'Shop'), ('office', 'Office'), ('warehouse', 'Warehouse')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['property'], name='properties__propert_79ed78_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['is_available'], name='properties__is_avai_2a217a_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['is_published'], name='properties__is_publ_4e1118_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['monthly_rent'], name='properties__monthly_569785_idx'),
        ),
    ]
