# Generated by Django 5.0.14 on 2026-05-14 10:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_type', models.CharField(choices=[('rent', 'Rent'), ('deposit', 'Deposit'), ('utility', 'Utility'), ('maintenance', 'Maintenance'), ('late_fee', 'Late Fee'), ('other', 'Other')], default='rent', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('description', models.TextField()),
                ('line_items', models.JSONField(blank=True, default=list)),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('late_fee_applied', models.BooleanField(default=False)),
                ('reminder_count', models.IntegerField(default=0)),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True)),
                ('mpesa_checkout_request_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invoices', to='tenants.lease')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(default='payment_due', max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('both', 'Both')], default='sms', max_length=10)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='invoices.invoice')),
            ],
        ),
    ]
