# Generated by Django 5.0.14 on 2026-05-09 13:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_tenantprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_type', models.CharField(choices=[('rent', 'Rent'), ('deposit', 'Deposit'), ('utility', 'Utility'), ('maintenance', 'Maintenance'), ('late_fee', 'Late Fee'), ('other', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('description', models.TextField()),
                ('line_items', models.JSONField(blank=True, default=list)),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('late_fee_applied', models.BooleanField(default=False)),
                ('reminder_count', models.IntegerField(default=0)),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True)),
                ('mpesa_checkout_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invoices', to='tenants.lease')),
            ],
            options={
                'ordering': ['-due_date'],
                'indexes': [models.Index(fields=['lease'], name='invoices_in_lease_i_27d960_idx'), models.Index(fields=['status'], name='invoices_in_status_cec546_idx'), models.Index(fields=['due_date'], name='invoices_in_due_dat_6cc0ed_idx')],
            },
        ),
    ]
