# Generated by Django 5.0.14 on 2026-05-09 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField()),
                ('tenant_name', models.CharField(max_length=255)),
                ('property_name', models.CharField(max_length=255)),
                ('unit_number', models.CharField(max_length=50)),
                ('invoice_number', models.CharField(max_length=50)),
                ('pdf_url', models.URLField(blank=True, max_length=500, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='receipt', to='payments.payment')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['payment'], name='invoices_re_payment_e95e3d_idx'), models.Index(fields=['receipt_number'], name='invoices_re_receipt_86a160_idx')],
            },
        ),
    ]
