# Generated by Django 5.0.14 on 2026-05-09 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0004_alter_unit_options_remove_unit_amenities_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_number', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_day', models.IntegerField(default=5)),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partially_refunded', 'Partially Refunded'), ('fully_refunded', 'Fully Refunded')], default='pending', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('renewed', 'Renewed')], default='active', max_length=20)),
                ('is_renewable', models.BooleanField(default=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('lease_document', models.URLField(blank=True, max_length=500, null=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('termination_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(limit_choices_to={'user_type': 'tenant'}, on_delete=django.db.models.deletion.RESTRICT, related_name='tenant_leases', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='leases', to='properties.unit')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['tenant'], name='tenants_lea_tenant__c7614d_idx'), models.Index(fields=['unit'], name='tenants_lea_unit_id_4a8c11_idx'), models.Index(fields=['status'], name='tenants_lea_status_727402_idx'), models.Index(fields=['start_date', 'end_date'], name='tenants_lea_start_d_61fc39_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('unit',), name='unique_active_lease_per_unit'),
        ),
    ]
