# Generated by Django 5.0.14 on 2026-05-14 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_number', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_day', models.IntegerField(default=5)),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partially_refunded', 'Partially Refunded'), ('fully_refunded', 'Fully Refunded')], default='pending', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('renewed', 'Renewed')], default='active', max_length=20)),
                ('is_renewable', models.BooleanField(default=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('lease_document', models.FileField(blank=True, null=True, upload_to='leases/')),
                ('terms_accepted', models.BooleanField(default=False)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('termination_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(limit_choices_to={'user_type': 'tenant'}, on_delete=django.db.models.deletion.RESTRICT, related_name='leases', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='leases', to='properties.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(blank=True, default='', max_length=255)),
                ('employer_address', models.TextField(blank=True, default='')),
                ('job_title', models.CharField(blank=True, default='', max_length=100)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('self_employed', 'Self Employed'), ('student', 'Student')], default='', max_length=50)),
                ('emergency_contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, default='', max_length=15)),
                ('referee_name', models.CharField(blank=True, default='', max_length=255)),
                ('referee_phone', models.CharField(blank=True, default='', max_length=15)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('employment_letter', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('tenant_score', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('payment_history_score', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
