# Generated by Django 5.0.14 on 2026-05-09 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('employer_address', models.TextField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('self_employed', 'Self Employed'), ('student', 'Student')], max_length=50, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('referee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('referee_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('id_document', models.URLField(blank=True, max_length=500, null=True)),
                ('employment_letter', models.URLField(blank=True, max_length=500, null=True)),
                ('tenant_score', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('payment_history_score', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'tenant'}, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
